import { EntityType } from '../types/ha-entity';

/** Maps entities to their type. Only entities in this map are tracked. */
export const entityTypeMap: {[key: string]: EntityType} = {
    'switch.marble_lamp': EntityType.Light,
    'switch.pendant_lamp': EntityType.Light,
    'light.family_room_lights': EntityType.Light,
    'light.family_room_chandelier': EntityType.Light,
    'switch.cat_den': EntityType.Light,
    'switch.kitchen_chandelier': EntityType.Light,
    'switch.kitchen_lights': EntityType.Light,
    'light.master_light': EntityType.Light,
    'switch.front_door_lights': EntityType.Light,
    'switch.outdoor_lights': EntityType.Light,
    'switch.christmas_tree': EntityType.Light,
    'light.standing_lamp': EntityType.Light,
    'light.entry_sconces': EntityType.Light,
    'sensor.synology_nas_cpu_utilization_total': EntityType.Gauge,
    'sensor.synology_nas_memory_usage_real': EntityType.Gauge,
    'sensor.udr_memory_utilization': EntityType.Gauge,
    'sensor.synology_nas_volume_1_volume_used': EntityType.Gauge,
    'sensor.udr_storage_utilization': EntityType.Gauge,
    'sensor.online_devices': EntityType.Gauge,
    'sensor.1m_download_max': EntityType.Gauge,
    'sensor.1m_upload_max': EntityType.Gauge,
    'sensor.top_download_device': EntityType.Gauge,
    'sensor.top_upload_device': EntityType.Gauge,
    'sensor.udr_cpu': EntityType.Gauge,
    'sensor.udr_mem': EntityType.Gauge,
    'camera.garage_cam_high': EntityType.Camera,
    'camera.family_room_cam_high': EntityType.Camera,
    'camera.bedroom_cam_high': EntityType.Camera,
    'camera.kitchen_cam_high': EntityType.Camera,
    'camera.litterbox_cam_high': EntityType.Camera,
    // 'camera.front_door': Type.Camera,
    // 'camera.front_yard_camera_2': Type.Camera,
    // 'camera.backyard_cam': Type.Camera,
    // 'camera.living_room_camera_2': Type.Camera,
    'sensor.nest_temperature_sensor_family_room_temperature': EntityType.Gauge,
    'sensor.master_bedroom_temperature_sensor_temperature': EntityType.Gauge,
    'sensor.thermostat_humidity': EntityType.Gauge,
    'sensor.adguard_home_dns_queries_blocked_ratio': EntityType.Gauge,
    'sensor.uck_g2_plus_cpu_temperature': EntityType.Gauge,
    'sensor.uck_g2_plus_storage_utilization': EntityType.Gauge,
    'cover.garage_door': EntityType.Garage,
    'switch.garage_cam_recording': EntityType.Switch,
    'switch.family_room_cam_recording': EntityType.Switch,
    'switch.bedroom_cam_recording': EntityType.Switch,
    'switch.kitchen_cam_recording': EntityType.Switch,
    'switch.litterbox_cam_recording': EntityType.Switch,
    'switch.air_purifier': EntityType.Switch,
    'switch.small_fan': EntityType.Switch,
    'switch.trash_day': EntityType.Switch,
    'select.trash_day': EntityType.Select,
    'switch.lawn_schedule': EntityType.Switch,
    'switch.roses_schedule_2': EntityType.Switch,
    'switch.backyard_primary': EntityType.Switch,
    'switch.backyard_secondary': EntityType.Switch,
    'switch.front_yard_primary': EntityType.Switch,
    'switch.front_yard_secondary': EntityType.Switch,
    'switch.backyard_drip': EntityType.Switch,
    'climate.thermostat': EntityType.Thermostat,
    'sensor.time': EntityType.Gauge,
    'sensor.date': EntityType.Gauge,
    'zone.home': EntityType.Gauge,
};
