/** Map of entities to rename */
export const renamedEntityMap: {[key: string]: string} = {
    'sensor.synology_nas_cpu_utilization_total': 'NAS CPU',
    'sensor.synology_nas_memory_usage_real': 'NAS RAM',
    'sensor.udr_cpu_utilization': 'UDR CPU',
    'sensor.udr_memory_utilization': 'UDR RAM',
    'sensor.synology_nas_volume_1_volume_used': 'NAS Storage',
    'sensor.1m_download_max': 'LAN Download',
    'sensor.1m_upload_max': 'Lan Upload',
    'sensor.top_download_device': 'Top Download',
    'sensor.top_upload_device': 'Top Upload',
    'sensor.udr_port_5_rx': 'Download',
    'sensor.udr_port_5_tx': 'Upload',
    'climate.ecobee_thermostat_2': 'Thermostat',
    'sensor.average_temperature': 'Average',
    'sensor.living_room_temperature_2': 'Temp',
    'sensor.ecobee_humidity': 'Humidity',
    'sensor.ecobee_air_quality_index': 'AQI',
    'sensor.ecobee_carbon_dioxide': 'CO2',
    'sensor.ecobee_vocs': 'VOCs',
    'sensor.family_room_temperature_2': 'Temp',
    'sensor.office_temperature_2': 'Temp',
    'sensor.master_bedroom_temperature_2': 'Temp',
    'sensor.little_room_temperature_2': 'Temp',
    'sensor.guest_bedroom_temperature_2': 'Temp',
    'sensor.adguard_home_dns_queries_blocked_ratio': 'AdGuard Blocked',
    'switch.lawn_schedule': 'Lawn',
    'switch.roses_schedule_2': 'Roses',
    'switch.backyard_primary': 'Back 1',
    'switch.backyard_secondary': 'Back 2',
    'switch.front_yard_primary': 'Front 1',
    'switch.front_yard_secondary': 'Front 2',
    'switch.backyard_drip': 'Drip',
    'sensor.uck_g2_plus_cpu_temperature': 'UCK CPU Temp',
    'sensor.uck_g2_plus_storage_utilization': 'UCK Storage',
    'camera.garage_cam_high': 'Garage Cam',
    'camera.family_room_cam_high': 'Family Room Cam',
    'camera.bedroom_cam_high': 'Bedroom Cam',
    'camera.kitchen_cam_high': 'Kitchen Cam',
    'camera.dining_room_cam_high': 'Dining Room Cam',
    'camera.front_door': 'Front Doorbell',
    'camera.living_room_cam_high_2': 'Living Room Cam',
    'camera.driveway_cam_high_2': 'Driveway Cam',
    'camera.front_yard_cam_high_3': 'Front Yard Cam',
    'camera.backyard_cam_high': 'Back Yard Cam',
    'sensor.processor_temperature': 'NAS Temp',
    'sensor.m440i_xdrive_mileage': 'Mileage',
    'sensor.m440i_xdrive_remaining_fuel_percent': 'Fuel',
};
